spec:
  template:
    spec:
      serviceAccount: salesforce-oauth-webapp
      volumes:
      - name: salesforce-ipaas-setup
        secret:
          secretName: salesforce.ipaas.setup
      containers:
      - volumeMounts:
        - name: salesforce-ipaas-setup
          readOnly: true
          mountPath: /var/run/secrets/salesforce
        env:
        - name: JAVA_OPTIONS
          value: -Djava.security.egd=file:/dev/./urandom